
GET http://localhost:8080/api/anime
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFmNmI1ZDc2MzYwYjNkYjRjZjM2YjUiLCJpYXQiOjE2MjI1NTMxMjl9.F6fc8IaGwmVpuH7sy-RRkCFxl-o0LnhcZwnJIpeT_9g
Content-Type: application/json

###

GET http://localhost:8080/api/word