
GET http://localhost:8080/api/document?type=NodeJS&id=60a8e7e56962c17fdbe0bf18
###
POST http://localhost:8080/api/document/create
###
DELETE http://localhost:8080/api/document/9123821379012839/delete
###
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
    "fullname":"Pham Long Huan",
    "username":"Huong",
    "password":"Kelkifa123"
}

### 
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
    "username":"huan",
    "password":"Kelkifa123"
}

###

GET http://localhost:8080/api/anime
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFmNmI1ZDc2MzYwYjNkYjRjZjM2YjUiLCJpYXQiOjE2MjI1NTMxMjl9.F6fc8IaGwmVpuH7sy-RRkCFxl-o0LnhcZwnJIpeT_9g

###
GET http://localhost:8080/api/document?type=IOT&update=60a1dadead1dc710148b7834

###

GET http://localhost:8080/api/user/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGFmNmI1ZDc2MzYwYjNkYjRjZjM2YjUiLCJpYXQiOjE2MjI2MTQ2MTN9.mRfUtNjFmFYFxy6Ly2o54XTIN0klbCES7G6U00F09K0